#!/bin/bash
# Verification script for feat-add-google-ai-studio-as-a-built-in-model-prov-vm1hxhqz
# Generated by relay-patch. Add patch-specific criteria below.
set -e

# Core: run the project's test suite
bun test

# Add patch-specific criteria here:
# Example:
# git diff --quiet upstream/main -- game.ts
# echo "" | bun run index.ts --some-flag | grep -q "expected output"
