#!/bin/bash
# Verification script for defer-d-bus-export-to-idle-to-avoid-gc-sweep-block-yt50fhbb
# Generated by forkhub. Add patch-specific criteria below.
set -e

# Core: run the project's test suite
bun test

# Add patch-specific criteria here:
# Example:
# git diff --quiet upstream/main -- game.ts
# echo "" | bun run index.ts --some-flag | grep -q "expected output"
