#!/bin/bash
# Verification script for feat-support-multiple-api-keys-profiles-for-managi-2cvkt133
# Generated by forkhub. Add patch-specific criteria below.
set -e

# Core: run the project's test suite
bun test

# Add patch-specific criteria here:
# Example:
# git diff --quiet upstream/main -- game.ts
# echo "" | bun run index.ts --some-flag | grep -q "expected output"
